<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('barangs')->delete();
        
        $data = [
            [
                'id' => 1,
                'nama' => 'Air Max 9000',
                'kategori' => 'Sneakers',
                'merk_id' => 1,
                'ukuran' => '42',
                'warna' => 'White',
                'harga' => '1899000.00',
                'stok' => 15,
                'deskripsi' => 'Ikon legendaris Nike Air Max 90 dengan cushioning Air yang responsif. Desain klasik yang tak lekang waktu, cocok untuk gaya kasual sehari-hari.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-16 07:45:55',
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'nama' => 'Air Force 1 Low',
                'kategori' => 'Sneakers',
                'merk_id' => 1,
                'ukuran' => '43',
                'warna' => 'White',
                'harga' => '1549000.00',
                'stok' => 20,
                'deskripsi' => 'Sepatu basket ikonik yang telah menjadi simbol budaya street style sejak 1982. Upper kulit premium dengan outsole rubber yang tahan lama.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'nama' => 'Zoom Pegasus 41',
                'kategori' => 'Running',
                'merk_id' => 1,
                'ukuran' => '42',
                'warna' => 'Black',
                'harga' => '1799000.00',
                'stok' => 12,
                'deskripsi' => 'Sepatu lari andalan Nike dengan teknologi Zoom Air unit di forefoot. Ringan, responsif, dan nyaman untuk lari harian maupun tempo.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'nama' => 'Dunk Low Retro',
                'kategori' => 'Sneakers',
                'merk_id' => 1,
                'ukuran' => '41',
                'warna' => 'Black/White',
                'harga' => '1649000.00',
                'stok' => 8,
                'deskripsi' => 'Tampilan klasik dunk yang digemari para sneakerhead. Padded collar untuk kenyamanan ekstra, cocok untuk skateboarding maupun daily wear.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'nama' => 'Revolution 7',
                'kategori' => 'Running',
                'merk_id' => 1,
                'ukuran' => '44',
                'warna' => 'Navy',
                'harga' => '899000.00',
                'stok' => 25,
                'deskripsi' => 'Sepatu lari entry-level dengan cushioning yang lembut. Mesh upper breathable untuk sirkulasi udara optimal saat berlari.',
                'gambar' => 'products/running_blue.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'nama' => 'Ultraboost Light',
                'kategori' => 'Running',
                'merk_id' => 2,
                'ukuran' => '42',
                'warna' => 'Core Black',
                'harga' => '2800000.00',
                'stok' => 10,
                'deskripsi' => 'Teknologi BOOST paling responsif dari Adidas. 30% lebih ringan dari Ultraboost sebelumnya dengan upper Primeknit+ yang adaptif.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'nama' => 'Stan Smith',
                'kategori' => 'Sneakers',
                'merk_id' => 2,
                'ukuran' => '43',
                'warna' => 'White/Green',
                'harga' => '1400000.00',
                'stok' => 18,
                'deskripsi' => 'Sneaker paling ikonik sepanjang masa. Desain minimalis dengan upper kulit halus dan signature perforated 3-Stripes.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:41',
                'updated_at' => '2026-07-15 08:14:41',
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'nama' => 'Samba OG',
                'kategori' => 'Sneakers',
                'merk_id' => 2,
                'ukuran' => '41',
                'warna' => 'White/Black',
                'harga' => '1600000.00',
                'stok' => 14,
                'deskripsi' => 'Lahir di lapangan futsal, kini menjadi favorit fashion. Suede T-toe, gum sole klasik, dan siluet yang timeless.',
                'gambar' => 'products/suede_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'nama' => 'Gazelle Indoor',
                'kategori' => 'Sneakers',
                'merk_id' => 2,
                'ukuran' => '42',
                'warna' => 'Collegiate Green',
                'harga' => '1500000.00',
                'stok' => 11,
                'deskripsi' => 'Versi indoor dari ikon retro Gazelle. Upper suede premium dengan gum outsole yang memberikan tampilan vintage autentik.',
                'gambar' => 'products/suede_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'nama' => 'Suede Classic XXI',
                'kategori' => 'Sneakers',
                'merk_id' => 3,
                'ukuran' => '42',
                'warna' => 'Black',
                'harga' => '1099000.00',
                'stok' => 16,
                'deskripsi' => 'Sneaker heritage Puma yang telah mewarnai budaya hip-hop dan skateboarding sejak 1968. Suede upper dengan formstrip klasik.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'nama' => 'RS-X Reinvention',
                'kategori' => 'Sneakers',
                'merk_id' => 3,
                'ukuran' => '43',
                'warna' => 'White/Royal',
                'harga' => '1499000.00',
                'stok' => 9,
                'deskripsi' => 'Chunky sneaker dengan teknologi Running System. Desain retro-futuristik dengan cushioning yang nyaman untuk aktivitas seharian.',
                'gambar' => 'products/retro_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'nama' => 'Velocity Nitro 3',
                'kategori' => 'Running',
                'merk_id' => 3,
                'ukuran' => '44',
                'warna' => 'Lime',
                'harga' => '1899000.00',
                'stok' => 7,
                'deskripsi' => 'Sepatu lari performa tinggi dengan foam NITRO™ yang ringan dan responsif. Grip PUMAGRIP untuk traksi di berbagai permukaan.',
                'gambar' => 'products/running_lime.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'nama' => '574 Core',
                'kategori' => 'Sneakers',
                'merk_id' => 4,
                'ukuran' => '42',
                'warna' => 'Grey',
                'harga' => '1299000.00',
                'stok' => 20,
                'deskripsi' => 'Sneaker paling populer dari New Balance. Kombinasi suede dan mesh dengan ENCAP midsole untuk kenyamanan sepanjang hari.',
                'gambar' => 'products/retro_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'nama' => '990v6 Made in USA',
                'kategori' => 'Sneakers',
                'merk_id' => 4,
                'ukuran' => '43',
                'warna' => 'Grey',
                'harga' => '3299000.00',
                'stok' => 5,
                'deskripsi' => 'Flagship premium New Balance, buatan tangan di AS. FuelCell midsole untuk cushioning superior dan pigskin suede upper.',
                'gambar' => 'products/retro_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 15,
                'nama' => 'Fresh Foam X 1080v13',
                'kategori' => 'Running',
                'merk_id' => 4,
                'ukuran' => '42',
                'warna' => 'Blue',
                'harga' => '2199000.00',
                'stok' => 10,
                'deskripsi' => 'Sepatu lari premium dengan Fresh Foam X cushioning paling empuk. Hypoknit upper yang adaptif dan breathable.',
                'gambar' => 'products/running_blue.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'nama' => '530',
                'kategori' => 'Sneakers',
                'merk_id' => 4,
                'ukuran' => '41',
                'warna' => 'White/Silver',
                'harga' => '1399000.00',
                'stok' => 13,
                'deskripsi' => 'Retro runner dari era Y2K dengan ABZORB cushioning. Desain chunky yang kembali populer di kalangan fashion enthusiast.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'nama' => 'Chuck Taylor All Star Hi',
                'kategori' => 'Sneakers',
                'merk_id' => 5,
                'ukuran' => '42',
                'warna' => 'Black',
                'harga' => '799000.00',
                'stok' => 30,
                'deskripsi' => 'Sepatu paling ikonik dalam sejarah. Canvas upper yang ringan dengan rubber toe cap dan ankle patch legendaris.',
                'gambar' => 'products/hightop_canvas.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'nama' => 'Chuck 70 Low',
                'kategori' => 'Sneakers',
                'merk_id' => 5,
                'ukuran' => '41',
                'warna' => 'Parchment',
                'harga' => '1099000.00',
                'stok' => 15,
                'deskripsi' => 'Versi premium dari Chuck Taylor dengan canvas yang lebih tebal, insole OrthoLite, dan detail vintage yang autentik.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'nama' => 'Old Skool',
                'kategori' => 'Sneakers',
                'merk_id' => 6,
                'ukuran' => '42',
                'warna' => 'Black/White',
                'harga' => '899000.00',
                'stok' => 22,
                'deskripsi' => 'Ikon skateboarding dengan sidestripe yang legendaris. Canvas dan suede upper dengan waffle outsole untuk board feel yang optimal.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'nama' => 'Sk8-Hi',
                'kategori' => 'Sneakers',
                'merk_id' => 6,
                'ukuran' => '43',
                'warna' => 'Black',
                'harga' => '999000.00',
                'stok' => 14,
                'deskripsi' => 'High-top klasik Vans dengan padded collar untuk ankle support. Desain yang telah menjadi simbol budaya skate dan punk.',
                'gambar' => 'products/hightop_canvas.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 21,
                'nama' => 'Classic Leather',
                'kategori' => 'Sneakers',
                'merk_id' => 7,
                'ukuran' => '42',
                'warna' => 'White',
                'harga' => '1199000.00',
                'stok' => 12,
                'deskripsi' => 'Heritage sneaker dengan upper kulit garment yang lembut. Die-cut EVA midsole untuk cushioning ringan dan nyaman.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 22,
                'nama' => 'Club C 85',
                'kategori' => 'Sneakers',
                'merk_id' => 7,
                'ukuran' => '43',
                'warna' => 'White/Green',
                'harga' => '1099000.00',
                'stok' => 10,
                'deskripsi' => 'Tennis shoe dari 1985 yang menjadi ikon lifestyle. Soft leather upper dengan clean lines yang timeless.',
                'gambar' => 'products/sneaker_white.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 23,
                'nama' => 'Gel-Kayano 31',
                'kategori' => 'Running',
                'merk_id' => 8,
                'ukuran' => '43',
                'warna' => 'Black/Blue',
                'harga' => '2399000.00',
                'stok' => 8,
                'deskripsi' => 'Stability running shoe legendaris dengan GEL™ technology dan 4D GUIDANCE SYSTEM. Ideal untuk overpronator.',
                'gambar' => 'products/running_blue.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 24,
                'nama' => 'Gel-1130',
                'kategori' => 'Sneakers',
                'merk_id' => 8,
                'ukuran' => '42',
                'warna' => 'White/Clay',
                'harga' => '1699000.00',
                'stok' => 11,
                'deskripsi' => 'Retro runner Y2K yang sedang tren. GEL cushioning di rearfoot dengan desain chunky yang fotogenik dan nyaman.',
                'gambar' => 'products/retro_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 25,
                'nama' => 'Go Walk 7',
                'kategori' => 'Casual',
                'merk_id' => 9,
                'ukuran' => '43',
                'warna' => 'Black',
                'harga' => '999000.00',
                'stok' => 18,
                'deskripsi' => 'Ultra-comfortable walking shoe dengan Hyper Pillar Technology™. Slip-on design yang praktis untuk aktivitas sehari-hari.',
                'gambar' => 'products/sneaker_black.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 26,
                'nama' => 'D\'Lites Fresh Start',
                'kategori' => 'Sneakers',
                'merk_id' => 9,
                'ukuran' => '40',
                'warna' => 'White/Navy',
                'harga' => '1099000.00',
                'stok' => 15,
                'deskripsi' => 'Chunky sneaker populer dengan Air-Cooled Memory Foam insole. Leather upper yang tahan lama dengan platform sole.',
                'gambar' => 'products/retro_sneaker.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 27,
                'nama' => 'Classic Chelsea Boot',
                'kategori' => 'Boots',
                'merk_id' => 10,
                'ukuran' => '42',
                'warna' => 'Black',
                'harga' => '2899000.00',
                'stok' => 6,
                'deskripsi' => 'Boots Chelsea klasik dengan Smooth leather dan AirWair™ bouncing soles. Elastic side panels untuk kemudahan pemakaian.',
                'gambar' => 'products/chelsea_boot.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 28,
                'nama' => '1461 Oxford',
                'kategori' => 'Formal',
                'merk_id' => 10,
                'ukuran' => '43',
                'warna' => 'Black',
                'harga' => '2499000.00',
                'stok' => 7,
                'deskripsi' => 'Sepatu tiga lubang ikonik Dr. Martens. Smooth leather dengan yellow welt stitching yang menjadi signature brand.',
                'gambar' => 'products/oxford_formal.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 29,
                'nama' => 'Adilette Comfort',
                'kategori' => 'Sandal',
                'merk_id' => 2,
                'ukuran' => '42',
                'warna' => 'Black',
                'harga' => '599000.00',
                'stok' => 25,
                'deskripsi' => 'Slides klasik Adidas dengan Cloudfoam footbed untuk kenyamanan maksimal. 3-Stripes branding yang ikonik.',
                'gambar' => 'products/slide_sandal.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 30,
                'nama' => 'Benassi JDI',
                'kategori' => 'Sandal',
                'merk_id' => 1,
                'ukuran' => '43',
                'warna' => 'Black/White',
                'harga' => '449000.00',
                'stok' => 20,
                'deskripsi' => 'Slide ringan Nike untuk recovery setelah olahraga. Injected Phylon midsole dan textured footbed untuk pijatan lembut.',
                'gambar' => 'products/slide_sandal.png',
                'created_at' => '2026-07-15 08:14:42',
                'updated_at' => '2026-07-15 08:14:42',
                'deleted_at' => NULL,
            ],
            [
                'id' => 31,
                'nama' => 'test',
                'kategori' => 'Sneakers',
                'merk_id' => 1,
                'ukuran' => '42',
                'warna' => 'White',
                'harga' => '100000.00',
                'stok' => 0,
                'deskripsi' => NULL,
                'gambar' => NULL,
                'created_at' => '2026-07-15 08:40:36',
                'updated_at' => '2026-07-16 07:00:17',
                'deleted_at' => '2026-07-16 07:00:17',
            ],
            [
                'id' => 32,
                'nama' => 'Jordan',
                'kategori' => 'Sneakers',
                'merk_id' => 6,
                'ukuran' => '45',
                'warna' => 'White',
                'harga' => '500000.00',
                'stok' => 35,
                'deskripsi' => 'air jordan',
                'gambar' => NULL,
                'created_at' => '2026-07-16 07:13:19',
                'updated_at' => '2026-07-16 07:18:10',
                'deleted_at' => '2026-07-16 07:18:10',
            ],
        ];
        
        DB::table('barangs')->insert($data);
    }
}